puts "     lovelo   velove"
puts "   lovelovelovelovelove"
puts " lovelovelovelovelovelov"
puts "  lovelovelovelovelovelo"
puts "    lovelovelovelovelo"
puts "      lolovelovelo"
puts "        lovelove"
puts "           ve"